environment:
    # IAR 软件路径
    IAR_path: {
        # ver  path
        iar7.4: 'D:\Work\IAR',
        iar8.2: 'D:\Work\IAR8.20',
        iar8.3: 'D:\Work\IAR8.30'
    }

    # GCC 软件路径
    GCC_path: {
        '8.1.0': 'D:\Work\mingw64'
    }